package com.jackappsdev.password_manager.presentation.theme

import androidx.compose.ui.graphics.Color

// Colors Generated Using
// https://m3.material.io/theme-builder

// Light Colors
val primaryLight = Color(0xFF005FB0)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD5E3FF)
val onPrimaryContainerLight = Color(0xFF001C3B)
val secondaryLight = Color(0xFF3D5F90)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD5E3FF)
val onSecondaryContainerLight = Color(0xFF121C2B)
val tertiaryLight = Color(0xFF006398)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFCDE5FF)
val onTertiaryContainerLight = Color(0xFF001D31)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFDFBFF)
val onBackgroundLight = Color(0xFF1A1C1E)
val surfaceLight = Color(0xFFFDFBFF)
val onSurfaceLight = Color(0xFF1A1C1E)
val surfaceVariantLight = Color(0xFFE0E2EC)
val onSurfaceVariantLight = Color(0xFF43474E)
val outlineLight = Color(0xFF74777F)
val outlineVariantLight = Color(0xFFC3C6CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3035)
val inverseOnSurfaceLight = Color(0xFFF0F0F7)
val inversePrimaryLight = Color(0xFFA6C8FF)
val surfaceDimLight = Color(0xFFD9DAE0)
val surfaceBrightLight = Color(0xFFF9F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F3FA)
val surfaceContainerLight = Color(0xFFEDEDF4)
val surfaceContainerHighLight = Color(0xFFE7E8EE)
val surfaceContainerHighestLight = Color(0xFFE1E2E9)

// Dark Colors
val primaryDark = Color(0xFFA6C8FF)
val onPrimaryDark = Color(0xFF00315F)
val primaryContainerDark = Color(0xFF004787)
val onPrimaryContainerDark = Color(0xFFD5E3FF)
val secondaryDark = Color(0xFFBDC7DC)
val onSecondaryDark = Color(0xFF273141)
val secondaryContainerDark = Color(0xFF3D4758)
val onSecondaryContainerDark = Color(0xFFD9E3F8)
val tertiaryDark = Color(0xFF93CCFF)
val onTertiaryDark = Color(0xFF003351)
val tertiaryContainerDark = Color(0xFF004B74)
val onTertiaryContainerDark = Color(0xFFCDE5FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A1C1E)
val onBackgroundDark = Color(0xFFE3E2E6)
val surfaceDark = Color(0xFF1A1C1E)
val onSurfaceDark = Color(0xFFE3E2E6)
val surfaceVariantDark = Color(0xFF43474E)
val onSurfaceVariantDark = Color(0xFFC4C6CF)
val outlineDark = Color(0xFF8D9199)
val outlineVariantDark = Color(0xFF43474E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E2E6)
val inverseOnSurfaceDark = Color(0xFF1A1C1E)
val inversePrimaryDark = Color(0xFF005FB0)
val surfaceDimDark = Color(0xFF111318)
val surfaceBrightDark = Color(0xFF37393E)
val surfaceContainerLowestDark = Color(0xFF0C0E13)
val surfaceContainerLowDark = Color(0xFF191C20)
val surfaceContainerDark = Color(0xFF1D2024)
val surfaceContainerHighDark = Color(0xFF282A2F)
val surfaceContainerHighestDark = Color(0xFF32353A)
